name: Continuous Deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - run: git config user.name "RyanLafferty"
      - run: git config user.email "RyanLafferty@users.noreply.github.com"
      - run: npm install -g @vue/cli
      - run: yarn install
      - run: yarn run build
      - run: yarn run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GH_TOKEN }}