name: Continuous Deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - run: git config user.name "RyanLafferty"
      - run: git config user.email "rlafferty1@hotmail.com"
      - run: npm install -g @vue/cli
      - run: yarn install
      - run: yarn run build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.CI_GH_TOKEN }}
          user_name: ${{ secrets.CI_USER_NAME }}
          user_email: ${{ secrets.CI_USER_EMAIL }}
          publish_dir: ./dist
